before_script:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install --prefer-dist --no-interaction
stages:
  - test
  - deploy
test:
  script:
    - echo "OK"
deploy:
  script:
    - rsync -rltzuvO ./ /var/www/devops.va-aeroflot.su/public_html
    - composer install --prefer-dist --no-interaction
    - composer update
  only:
    - master