before_script:
  - composer install
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
deploy:
  script:
    - mv -v /* /var/www/dev.va-aeroflot.su/public_html
    - cd /var/www/dev.va-aeroflot.su/public_html
    - composer update