before_script:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install --prefer-dist --no-interaction
stages:
  - test
  - deploy_dev
  - deploy
test:
  script:
    - echo "OK"
deploy_dev:
  script:
    - rsync -rltzuvO ./ /var/www/dev.va-aeroflot.su/public_html
  only:
    - dev
deploy:
  script:
    - rsync -rltzuvO ./ /var/www/va-aeroflot.su/public_html
  only:
    - master