before_script:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer install
stages:
  - test
  - deploy
test:
  script:
    - echo "OK"
deploy:
  script:
    #- mv -v /* /var/www/dev.va-aeroflot.su/public_html
    #- cd /var/www/dev.va-aeroflot.su/public_html
    - composer update